# Generated by Django 4.2.8 on 2023-12-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='username',
            field=models.CharField(default=18.24, max_length=255),
            preserve_default=False,
        ),
    ]
