# Generated by Django 4.2.8 on 2023-12-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_personalinformation_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='username',
        ),
    ]
