# Generated by Django 4.2.8 on 2023-12-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_remove_personalinformation_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.branch'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='district',
            field=models.ForeignKey(default=0.09, on_delete=django.db.models.deletion.CASCADE, to='bankapp.district'),
            preserve_default=False,
        ),
    ]
